### ISSUE TITLE
Unable to make movie from command-line on quartz

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#93]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

A user (Niel Hodge) is unable to create a movie from command-line on quartz

```
visit -movie -format png -geometry 1200x1200 -sessionfile movie.session -output movie

(which worked as of the last time I tried it, maybe in the last six months or so) and this was the response:

Running: cli3.1.2 -nowin -s /usr/gapps/visit/3.1.2/linux-x86_64/bin/makemoviemain.py -format png -geometry 1200x1200 -sessionfile movie.session -output movie
Running: viewer3.1.2 -nowin -noint -format png -geometry 1200x1200 -sessionfile movie.session -output movie -host 127.0.0.1 -port 5600
Running: srun -n 32 -p pdebug /usr/gapps/visit/3.1.2/linux-x86_64/bin/engine_par -format png -sessionfile movie.session -output movie -forcestatic -idle-timeout 480 -host quartz386 -port 5600
Running: mdserver3.1.2 -format png -sessionfile movie.session -output movie -host 127.0.0.1 -port 5600
VisIt: Message - VisIt imported a session from: movie.session.
Traceback (most recent call last):
  File "/usr/gapps/visit/3.1.2/linux-x86_64/bin/makemoviemain.py", line 40, in <module>
    main()
  File "/usr/gapps/visit/3.1.2/linux-x86_64/bin/makemoviemain.py", line 32, in main
    if movie.GenerateFrames() > 0:
  File "/usr/gapps/visit/3.1.2/linux-x86_64/bin/makemovie.py", line 2453, in GenerateFrames
    RestoreSession(self.stateFile, 0)
visit.VisItException: VisIt's viewer has terminated abnormally!
```

When I've tried to duplicate...I am unable to get engine even to launch, either in mxterm or trying to run in pdebug on quartz. I can do it interactively though.

Have asked user to run with `-debug 5` and send debug logs.

**Comment by markcmiller86** [comment]
@brugger1 and @markcmiller86 spent time (probably a few hours between us) debugging and resolved but filed this [product development issue](https://github.com/visit-dav/visit/issues/4860)
